### ISSUE TITLE
It's not sorting based on score

### ISSUE THREAD

**Issue by ashu-89** [zepinos/leaderboard#2]
Hi,

I've used http://localhost:8080/admin/createLeaderboardInfo?name=Ashu&period=DAY&sort=DESC
to create multiple rows.

Then I used http://localhost:8080/leaderboard/appendScore?position=4&userId=4&score=6
to append score and user id.

And finally using http://localhost:8080/admin/listLeaderboardInfo?startPosition=0&endPosition=99

I expect the result of this api to be sorted based on score, but it's not sorting based on score.
It is simply returning in order of key's position !

So it's not really a leader-board !!

Also, I can see this : 

if (epochHashOperations.hasKey(currentEpochKey, userId)) {

			// TODO 마지막으로 점수를 저장한 timestamp 을 가져와 ZSet 에서 사용자의 등록된 점수 조회
			Long currentEpoch = epochHashOperations.get(currentEpochKey, userId);

			Double currentScore = zSetOperations.score(currentKey, currentEpoch + ":" + userId);

			if ((sort == Sort.ASC && currentScore.doubleValue() < score) ||
					(sort == Sort.DESC && currentScore > score)) {

				// TODO 현재 timestamp 와 점수를 저장

			}

		} else {

			// TODO 등록된 정보가 없다면 최초 등록이기 때문에 무조건 등록

		}

So main logic is for us //TODO !
And you haven't even used ZSET, but just kept it in comment.

So, this isn't very helpful, as it's not behaving like leader-board !

See, I've given different scores so the list should be sorted based on score, but see the output, it is not sorted based on score, but it is just appearing based on position.

http://localhost:8080/admin/listLeaderboardInfo?startPosition=0&endPosition=99

{
    "leaderboardInfoList": [
        {
            "name": "MyLeaderBoard001",
            "period": "DAY",
            "sort": "DESC",
            "status": "USE"
        },
        {
            "name": "MyLeaderBoard002",
            "period": "DAY",
            "sort": "DESC",
            "status": "USE"
        },
        {
            "name": "MyLeaderBoard003",
            "period": "DAY",
            "sort": "DESC",
            "status": "USE"
        },
        {
            "name": "Abhishek",
            "period": "DAY",
            "sort": "DESC",
            "status": "USE"
        },
        {
            "name": "Ashu",
            "period": "DAY",
            "sort": "DESC",
            "status": "USE"
        }
    ],
    "status": 0
}

Here, score of Abhishek is highest, then  my score, and leaderboard001, 2, 3 are also in different score !

So, please let me know asap, if I'm doing something wrong, or you haven't really implemented entire leaderboard.

Thanks and Regards,
Ashutosh Pathak

**Comment by zepinos** [comment]
First of all, please understand that my English is very poor and I will translate it into a Google Translator.

The source for this repository is incomplete. Personally, I made it to reveal the technology of the leaderboard of the game server that was commissioned and made at very low cost, but it was stopped due to personal circumstances.

This source will be closed soon. If you want to see the actual source code used on the game server (please do not disclose it to others), please contact me by email.

zepinos at gmail.com

Thanks.
zepinos.

**Comment by ashu-89** [comment]
Hi Jonghwa,

First of all thanks a lot for sharing your code. Any help is always
appreciated.

Second of all, as you mentioned "If you want to see the actual source code
used on the game server (please do not disclose it to others), please
contact me by email.", yes, It would help me immensely if I got to see the
actual code.
I will not disclose to others.

Thanks from India !

Thanks and Regards,
Ashutosh Pathak

**Comment by zepinos** [comment]
Hi ashu-89,

Please let me know your email address. I will send the source by email.

Thanks.
zepinos.

**Comment by ashu-89** [comment]
ashu.p89@gmail.com
Sorry for late reply !
